DROP TABLE IF EXISTS plants;
DROP TABLE IF EXISTS monsters;
DROP TABLE IF EXISTS skates;

CREATE TABLE plants (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  leaves INT CHECK (leaves > 0),
  height TEXT
);

CREATE TABLE monsters (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  creepFactor INT,
  phrase TEXT
);

CREATE TABLE skates (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  owner TEXT NOT NULL,
  brand TEXT,
  wheels INT
);


